INSERT INTO ingredient (name_lt, unit) VALUES
-- Daržovės
('Bulvės', 'G'),
('Morkos', 'G'),
('Svogūnai', 'G'),
('Česnakas', 'G'),
('Pomidorai', 'G'),
('Agurkai', 'G'),
('Paprikos', 'G'),
('Cukinijos', 'G'),
('Baklažanai', 'G'),
('Brokoliai', 'G'),
('Žiediniai kopūstai', 'G'),
('Kopūstai', 'G'),
('Špinatai', 'G'),
('Salotos', 'G'),
('Ridikėliai', 'G'),
('Burokėliai', 'G'),
('Ropės', 'G'),
('Pasternokos', 'G'),
('Saldžiosios bulvės', 'G'),
('Porai', 'G'),
('Žalieji žirneliai', 'G'),
('Kukurūzai', 'G'),
('Šparagai', 'G'),
('Grybai', 'G'),
('Pievagrybiai', 'G'),
('Moliūgai', 'G'),

-- Vaisiai ir uogos
('Obuoliai', 'G'),
('Kriaušės', 'G'),
('Bananai', 'G'),
('Apelsinai', 'G'),
('Mandarinai', 'G'),
('Citrinos', 'G'),
('Žaliosios citrinos', 'G'),
('Braškės', 'G'),
('Avietės', 'G'),
('Mėlynės', 'G'),
('Vyšnios', 'G'),
('Slyvos', 'G'),
('Persikai', 'G'),
('Vynuogės', 'G'),
('Arbūzai', 'G'),
('Melionai', 'G'),
('Kiviai', 'G'),
('Mangai', 'G'),
('Ananasai', 'G'),

-- Mėsa
('Vištienos krūtinėlė', 'G'),
('Vištienos šlaunelės', 'G'),
('Kiaulienos nugarinė', 'G'),
('Kiaulienos šonkauliai', 'G'),
('Kiaulienos maltinė', 'G'),
('Jautienos maltinė', 'G'),
('Jautiena', 'G'),
('Kalakutiena', 'G'),
('Antiena', 'G'),
('Triušiena', 'G'),
('Dešra', 'G'),
('Dešrelės', 'G'),
('Šoninė', 'G'),
('Kumpis', 'G'),
('Skilandis', 'G'),

-- Žuvis ir jūros gėrybės
('Lašiša', 'G'),
('Menkė', 'G'),
('Upėtakis', 'G'),
('Silkė', 'G'),
('Tunų konservai', 'G'),
('Krevetės', 'G'),
('Kalmurai', 'G'),
('Sardinės', 'G'),

-- Pieno produktai
('Pienas', 'ML'),
('Grietinė', 'ML'),
('Grietinėlė', 'ML'),
('Jogurtas', 'ML'),
('Kefyras', 'ML'),
('Varškė', 'G'),
('Sūris', 'G'),
('Mocarela', 'G'),
('Parmezanas', 'G'),
('Feta', 'G'),
('Mascarpone', 'G'),
('Sviestas', 'G'),

-- Kiaušiniai
('Kiaušiniai', 'VNT'),

-- Grūdai ir miltų produktai
('Kvietiniai miltai', 'G'),
('Rugių miltai', 'G'),
('Kukurūzų miltai', 'G'),
('Ryžiai', 'G'),
('Grikiai', 'G'),
('Perlinės kruopos', 'G'),
('Avižinės dribsniai', 'G'),
('Manų kruopos', 'G'),
('Kuskusas', 'G'),
('Bulguras', 'G'),
('Makaronai', 'G'),
('Spagečiai', 'G'),
('Lasanijos lakštai', 'G'),
('Duona', 'G'),
('Balta duona', 'G'),
('Juoda duona', 'G'),
('Tortilijos', 'VNT'),
('Lavašas', 'VNT'),

-- Ankštiniai
('Lęšiai', 'G'),
('Avinžirniai', 'G'),
('Raudonosios pupelės', 'G'),
('Baltosios pupelės', 'G'),

-- Riešutai ir sėklos
('Graikiniai riešutai', 'G'),
('Migdolai', 'G'),
('Lazdyno riešutai', 'G'),
('Žemės riešutai', 'G'),
('Saulėgrąžų sėklos', 'G'),
('Moliūgų sėklos', 'G'),
('Sezamo sėklos', 'G'),
('Linų sėmenys', 'G'),
('Čia sėklos', 'G'),

-- Aliejai ir riebalai
('Alyvuogių aliejus', 'ML'),
('Saulėgrąžų aliejus', 'ML'),
('Kokosų aliejus', 'ML'),
('Sviestinis aliejus', 'ML'),

-- Prieskoniai ir priedai
('Druska', 'G'),
('Pipirai', 'G'),
('Raudonieji pipirai', 'G'),
('Kmynai', 'G'),
('Cinamonas', 'G'),
('Imbieras', 'G'),
('Ciberžolė', 'G'),
('Rožmarinas', 'G'),
('Bazilikas', 'G'),
('Petražolės', 'G'),
('Krapai', 'G'),
('Lauro lapai', 'VNT'),
('Čiobreliai', 'G'),
('Oreganas', 'G'),
('Muskato riešutas', 'G'),
('Vanilinis cukrus', 'G'),
('Kepimo milteliai', 'G'),
('Soda', 'G'),

-- Padažai ir konservai
('Pomidorų padažas', 'ML'),
('Sojų padažas', 'ML'),
('Pomidorų pasta', 'G'),
('Garstyčios', 'G'),
('Majonezas', 'G'),
('Kečupas', 'ML'),
('Actas', 'ML'),
('Obuolių actas', 'ML'),
('Kokosų pienas', 'ML'),

-- Saldumynai ir saldikliai
('Cukrus', 'G'),
('Rudasis cukrus', 'G'),
('Medus', 'G'),
('Šokoladas', 'G'),
('Kakava', 'G'),

-- Gėrimai
('Vanduo', 'ML'),
('Sultys', 'ML');
